# Generated by Django 4.1.3 on 2022-12-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_juegos_mascota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
