# Generated by Django 4.1.3 on 2022-12-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_macotas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Macotas',
            new_name='Mascotas',
        ),
    ]
